=== revms42/Ajar-Game-Engine/java/trunk/data/MDJ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MDJ" elementFormDefault="qualified" xmlns:mdj="http://www.example.org/MDJ">
    <complexType name="Stat">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attributeGroup ref="mdj:StatGroup"></attributeGroup>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="double"></enumeration>
    				<enumeration value="float"></enumeration>
    				<enumeration value="long"></enumeration>
    				<enumeration value="int"></enumeration>
    				<enumeration value="short"></enumeration>
    				<enumeration value="byte"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>



    <attributeGroup name="StatGroup">
    	<attribute name="value" type="decimal" use="required"></attribute>
    	<attribute name="max" type="decimal" use="required"></attribute>
    	<attribute name="min" type="decimal" use="required"></attribute>
    	<attribute name="nominal" type="decimal" use="required"></attribute>
    </attributeGroup>






    <complexType name="Stats">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="Stat" type="mdj:Stat" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Action">
    	<sequence>
    		<element name="TargetStat" type="mdj:ActionArgument" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="FirstArgument" type="mdj:ActionArgument" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="SecondArgument" type="mdj:ActionArgument" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="add"></enumeration>
    				<enumeration value="subtract"></enumeration>
    				<enumeration value="multiply"></enumeration>
    				<enumeration value="divide"></enumeration>
    				<enumeration value="modulo"></enumeration>
    				<enumeration value="power"></enumeration>
    				<enumeration value="equals"></enumeration>
    				<enumeration value="and"></enumeration>
    				<enumeration value="or"></enumeration>
    				<enumeration value="xor"></enumeration>
    				<enumeration value="not"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>







    <complexType name="ActionList">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="Action" type="mdj:Action" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>







    <attributeGroup name="ImageBoardGroup">
    	<attribute name="location" type="anyURI" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="tileWidth" type="unsignedInt" use="required"></attribute>
    	<attribute name="tileHeight" type="unsignedInt" use="required"></attribute>
    </attributeGroup>

    <complexType name="ImageBoard"><attributeGroup ref="mdj:ImageBoardGroup"></attributeGroup></complexType>

    <complexType name="ImagePalette">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="ImageBoard" type="mdj:ImageBoard" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ActionArgument">
    	<choice minOccurs="1" maxOccurs="1">
    		<element name="Subject">
    			<complexType>
    				<attribute name="stat" type="string"
    					use="required">
    				</attribute>
    				<attribute name="property" use="required">
    					<simpleType>
    						<restriction base="string">
    							<enumeration value="value"></enumeration>
    							<enumeration value="max"></enumeration>
    							<enumeration value="min"></enumeration>
    							<enumeration value="nominal"></enumeration>
    						</restriction>
    					</simpleType>
    				</attribute>
    			</complexType>
    		</element>
    		<element name="Object">
    			<complexType>
    				<attribute name="stat" type="string"
    					use="required">
    				</attribute>
    				<attribute name="property" use="required">
    					<simpleType>
    						<restriction base="string">
    							<enumeration value="value"></enumeration>
    							<enumeration value="max"></enumeration>
    							<enumeration value="min"></enumeration>
    							<enumeration value="nominal"></enumeration>
    						</restriction>
    					</simpleType>
    				</attribute>
    			</complexType>
    		</element>
    		<element name="Number" type="decimal"></element>
    	</choice>
    </complexType>





    <complexType name="Environment">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="Palette" type="mdj:ImagePalette"
    			minOccurs="1" maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="blueprint" type="anyURI" use="required"></attribute>
    </complexType>

    <complexType name="Character">
 			<sequence minOccurs="1" maxOccurs="1">
 				<element name="Palette" type="mdj:ImagePalette"
 					minOccurs="1" maxOccurs="unbounded">
 				</element>
 				<element name="Stats" minOccurs="1" maxOccurs="unbounded">
 					<complexType>
 						<choice minOccurs="1" maxOccurs="1">
 							<element name="UniqueStats"
 								type="mdj:Stats">
 							</element>
 							<element name="UniqueStat"
 								type="mdj:Stat">
 							</element>
 							<element name="DefaultStats" type="string"></element>
 						</choice>
 					</complexType></element>
 			</sequence>
 			<attribute name="name" type="string"></attribute>
 			<attribute name="controller">
 				<simpleType>
 					<restriction base="string">
 						<enumeration value="player"></enumeration>
 						<enumeration value="AI"></enumeration>
 					</restriction>
 				</simpleType>
 			</attribute>
    </complexType>
    



    <complexType name="ConditionArgument">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="FirstArg" type="mdj:ActionArgument"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="SecondArg" type="mdj:ActionArgument" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="equal"></enumeration>
    				<enumeration value="greaterThan"></enumeration>
    				<enumeration value="lessThan"></enumeration>
    				<enumeration value="greaterOrEqual"></enumeration>
    				<enumeration value="lessOrEqual"></enumeration>
    				<enumeration value="notEqual"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="Condition">
    	<sequence>
    		<element name="Condition" type="mdj:ConditionArgument"
    			minOccurs="1" maxOccurs="1">
    		</element>


    		<element name="ActionsPerformed" type="string" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="actionPalette" type="string"></attribute>
    	<attribute name="memberOfActionPalette" type="string"></attribute>
    </complexType>


    <complexType name="SimpleGame">
    	<sequence>
    		<element name="GameCharacter" type="mdj:Character"
    			minOccurs="1" maxOccurs="unbounded">
    		</element>
    		<element name="Level" type="mdj:Environment" minOccurs="1"
    			maxOccurs="1">
    		</element>

    		<element name="GameCondition" type="mdj:Condition"
    			minOccurs="1" maxOccurs="unbounded">
    		</element>
    		<element name="DefaultStats" minOccurs="0" maxOccurs="unbounded">
    			<complexType>
    				<sequence>
    					<element name="Stats" type="mdj:Stats"
    						minOccurs="1" maxOccurs="1">
    					</element>
    				</sequence>
    				<attribute name="name" type="string"></attribute>
    			</complexType>
    		</element>
    		<element name="ActionPalette" type="mdj:ActionList" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="onTurnCondition" type="string"></attribute>
    	<attribute name="endCondition" type="string"></attribute>
    </complexType>

    <element name="GameDescription" type="mdj:SimpleGame"></element>

    <element name="TurnDescription" type="mdj:SimpleTurn"></element>

    <complexType name="SimpleTurn">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<element name="CharacterActions" type="mdj:CharacterActionQueue"></element>
    	</sequence>
    </complexType>

    <complexType name="CharacterActionQueue">
    	<sequence>
    		<element name="ConditionCall" type="mdj:ConditionCall"></element>
    	</sequence>
    	<attribute name="characterName" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ConditionCall">
    	<sequence>
    		<element name="subject" type="mdj:Character" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="object" type="mdj:Character" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="condition" type="string"></attribute>
    </complexType>

    <element name="TurnResults" type="mdj:SimpleTurnResults"></element>

    <complexType name="SimpleTurnResults">
    	<sequence>
    		<element name="Character" minOccurs="0" maxOccurs="unbounded">
    			<complexType>
    				<sequence>
    					<element name="Character"
    						type="mdj:Character" minOccurs="1" maxOccurs="1">
    					</element>
    					<element name="Effect" minOccurs="1" maxOccurs="1">
    						<complexType>

    							<attribute name="stat" type="string" use="required">
    							</attribute>
    							<attribute name="effect"
    								type="decimal" use="required">
    							</attribute>
    						</complexType></element>
    				</sequence>
    			</complexType></element>
    	</sequence>
    </complexType>
</schema>

=== revms42/Ajar-Game-Engine/java/trunk/data/MDJ.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdj:GameDescription endCondition="end" onTurnCondition="move" xmlns:mdj="http://www.example.org/MDJ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/MDJ ../../bin/data/MDJ.xsd ">

  <mdj:GameCharacter controller="AI" name="square">
    <mdj:Palette>
      <mdj:ImageBoard location="http://tempuri.org" name="square" tileHeight="20" tileWidth="20"/>
    </mdj:Palette>
    <mdj:Stats>
    	<mdj:DefaultStats>default</mdj:DefaultStats>
    </mdj:Stats>
  </mdj:GameCharacter>
  
  <mdj:Level blueprint="http://tempuri.org" name="level">
    <mdj:Palette>
      <mdj:ImageBoard location="http://tempuri.org" name="blueprint" tileHeight="200" tileWidth="200"/>
    </mdj:Palette>
  </mdj:Level>
  
  <mdj:GameCondition actionPalette="default" memberOfActionPalette="default" name="flipX-FE">
    <mdj:Condition type="greaterOrEqual">
      <mdj:FirstArg>
        <mdj:Subject property="value" stat="x"/>
      </mdj:FirstArg>
      <mdj:SecondArg>
        <mdj:Subject property="max" stat="x"/>
      </mdj:SecondArg>
    </mdj:Condition>
    <mdj:ActionsPerformed>revDx</mdj:ActionsPerformed>
  </mdj:GameCondition>
  
  <mdj:GameCondition actionPalette="default" memberOfActionPalette="default" name="flipY-FE">
    <mdj:Condition type="greaterOrEqual">
      <mdj:FirstArg>
        <mdj:Subject property="value" stat="y"/>
      </mdj:FirstArg>
      <mdj:SecondArg>
        <mdj:Subject property="max" stat="y"/>
      </mdj:SecondArg>
    </mdj:Condition>
    <mdj:ActionsPerformed>revDy</mdj:ActionsPerformed>
  </mdj:GameCondition>
  
  <mdj:GameCondition actionPalette="default" memberOfActionPalette="default" name="flipX-NE">
    <mdj:Condition type="lessOrEqual">
      <mdj:FirstArg>
        <mdj:Subject property="value" stat="x"/>
      </mdj:FirstArg>
      <mdj:SecondArg>
        <mdj:Subject property="min" stat="x"/>
      </mdj:SecondArg>
    </mdj:Condition>
    <mdj:ActionsPerformed>revDx</mdj:ActionsPerformed>
  </mdj:GameCondition>
  
  <mdj:GameCondition actionPalette="default" memberOfActionPalette="default" name="flipY-NE">
    <mdj:Condition type="lessOrEqual">
      <mdj:FirstArg>
        <mdj:Subject property="value" stat="y"/>
      </mdj:FirstArg>
      <mdj:SecondArg>
        <mdj:Subject property="min" stat="y"/>
      </mdj:SecondArg>
    </mdj:Condition>
    <mdj:ActionsPerformed>revDy</mdj:ActionsPerformed>
  </mdj:GameCondition>
  
  <mdj:GameCondition name="move">
  
  	<mdj:Condition type="lessThan">
  		<mdj:FirstArg>
  			<mdj:Subject stat="bounces" property="value" />
  		</mdj:FirstArg>
  		<mdj:SecondArg>
  			<mdj:Subject stat="bounces" property="max" />
  		</mdj:SecondArg>
  	</mdj:Condition>
  	
  	<mdj:ActionsPerformed>incriX</mdj:ActionsPerformed>
  	<mdj:ActionsPerformed>incriY</mdj:ActionsPerformed>
  	<mdj:ActionsPerformed>flipX-NE</mdj:ActionsPerformed>
  	<mdj:ActionsPerformed>flipX-FE</mdj:ActionsPerformed>
  	<mdj:ActionsPerformed>flipY-NE</mdj:ActionsPerformed>
  	<mdj:ActionsPerformed>flipY-FE</mdj:ActionsPerformed>
  	
  </mdj:GameCondition>
  
  <mdj:GameCondition name="end">
  	<mdj:Condition type="greaterOrEqual">
  		<mdj:FirstArg>
  			<mdj:Subject stat="bounces" property="value" />
  		</mdj:FirstArg>
  		<mdj:SecondArg>
  			<mdj:Subject stat="bounces" property="max" />
  		</mdj:SecondArg>
  	</mdj:Condition>
  </mdj:GameCondition>

  <mdj:DefaultStats name="default">
    <mdj:Stats>
      <mdj:Stat max="200" min="0" name="x" nominal="10" value="100" type="int"/>
      <mdj:Stat max="200" min="0" name="y" nominal="10" value="10" type="int"/>
      <mdj:Stat max="10" min="-10" name="dx" nominal="1" value="1" type="int"/>
      <mdj:Stat max="10" min="-10" name="dy" nominal="1" value="1" type="int"/>
      <mdj:Stat	max="20" name="bounces" min="0" value="0" nominal="0" type="int" />
    </mdj:Stats>
  </mdj:DefaultStats>
  
  <mdj:ActionPalette name="default">
  
    <mdj:Action name="incriX" type="add">
      <mdj:TargetStat>
      	<mdj:Subject property="value" stat="x"/>
      </mdj:TargetStat>
      <mdj:FirstArgument>
        <mdj:Subject property="value" stat="x"/>
      </mdj:FirstArgument>
      <mdj:SecondArgument>
        <mdj:Subject property="value" stat="dx"/>
      </mdj:SecondArgument>
    </mdj:Action>
    
    <mdj:Action name="incriY" type="add">
      <mdj:TargetStat>
      	<mdj:Subject property="value" stat="y"/>
      </mdj:TargetStat>
      <mdj:FirstArgument>
        <mdj:Subject property="value" stat="y"/>
      </mdj:FirstArgument>
      <mdj:SecondArgument>
        <mdj:Subject property="value" stat="dy"/>
      </mdj:SecondArgument>
    </mdj:Action>
    
    <mdj:Action name="revDx" type="multiply">
    	<mdj:TargetStat>
    		<mdj:Subject stat="dx" property="value" />
    	</mdj:TargetStat>
    	<mdj:FirstArgument>
    		<mdj:Subject stat="dx" property="value" />
    	</mdj:FirstArgument>
    	<mdj:SecondArgument>
    		<mdj:Number>-1</mdj:Number>
    	</mdj:SecondArgument>
    </mdj:Action>
    
    <mdj:Action name="revDy" type="multiply">
    	<mdj:TargetStat>
    		<mdj:Subject stat="dy" property="value" />
    	</mdj:TargetStat>
    	<mdj:FirstArgument>
    		<mdj:Subject stat="dy" property="value" />
    	</mdj:FirstArgument>
    	<mdj:SecondArgument>
    		<mdj:Number>-1</mdj:Number>
    	</mdj:SecondArgument>
    </mdj:Action>
    
  </mdj:ActionPalette>
  
</mdj:GameDescription>
